version: '3.8'

services:
  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    environment:
      - DB=sqlite:///app/db/filmesdb.db
    ports:
      - "8000:8000"
    volumes:
      - ./BackEnd:/App
      - sqlite-data:/app/db

  frontend:
    build:
      context: ./FrontEnd/movie-catalog
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./FrontEnd/movie-catalog:/App

  sqlite:
    image: alpine
    volumes:
      - sqlite-data:/app/db
    command: >
      sh -c "touch /app/db/filmesdb.db && chmod 666 /app/db/filmesdb.db && tail -f /dev/null"

volumes:
  sqlite-data: